name: "\U0001F41B [Bug report]: "
description: Create a report to help us improve
title: "\U0001F41B [Bug report]: "
labels: ["bug", "triage"]
assignees: [""]
body:
#   - type: markdown
#     attributes:
#       value: |
#         Thanks for taking the time to fill out this bug report!
#   - type: input
#     id: contact
#     attributes:
#       label: Contact Details
#       description: How can we get in touch with you if we need more info?
#       placeholder: ex. email@example.com
#     validations:
#       required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Descrcibe the bug?
#       description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduce-step
    attributes:
      label: Steps to reproduce the bug?
      description: Steps to reproduce the behavior..
      placeholder: 1. Go to ..
                   2. Click on ..
                   

#       value: "A bug happened!"
    validations:
      required: true   
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.                   
    validations:
      required: true  
  - type: textarea
    id: desktop-browser
    attributes:
      label: Desktop (please provide your system information)
      description:  |
        examples
          - OS: [e.g. iOS]
          - Browser [e.g. chrome, safari]
          - Version [e.g. 22]                 
    validations:
      required: true  

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
#   - type: dropdown
#     id: browsers
#     attributes:
#       label: What browsers are you seeing the problem on?
#       multiple: true
#       options:
#         - Firefox
#         - Chrome
#         - Safari
#         - Microsoft Edge     
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot / Screenshare
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: additional-context
    attributes:
      label: Relevant log output
      description: Add any other context about the problem here.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/reactplay/react-play/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
